### ISSUE TITLE
gem dependencies not resolved in jenkins devel jobs

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/rosdistro#22]
see https://github.com/strands-project/rosdistro/pull/21 discovered by @hawesie

**Comment by marc-hanheide** [comment]
problem is that https://github.com/strands-project/jenkins_scripts/blob/master/test_repositories.py tries to resolve all dependencies via `apt-get` and not via rosdep.

Having investigated a bit further, that actually seems to make sense. If we want to deploy Debian packages, all dependencies must be Deb packages as well. So, we'd need a jekyll deb!

**Comment by marc-hanheide** [comment]
In other words: Also the build farm will only generate correct packages IF jekyll can be resolved on deb basis. That's also why I'm working to get MIRA released as a deb (agreed with MetraLabs).

**Comment by hawesie** [comment]
Poop.

**Comment by hawesie** [comment]
For the time being I will remove this from the distro.

**Comment by marc-hanheide** [comment]
Boo! ;-)

**Comment by marc-hanheide** [comment]
BTW... it shouldn't be too hard to do it. All you'd need is look at this http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty I suppose. But I don't know how easy it is to embed gem/ruby into this, as I have never used it.

Cheers,

Marc

**Comment by cdondrup** [comment]
It also breaks to rosdep call we currently use to install dependencies:

```
$ rosdep install --from-paths src --ignore-src --rosdistro hydro -y -r
WARNING: Package "libg2o" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).

ERROR: Rosdep experienced an internal error.
Please go to the rosdep page [1] and file a bug report with the message below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.10.30

Bad installer [gem]: [Errno 2] No such file or directory
```

**Comment by hawesie** [comment]
It might be that I can fix this latter problem with a `buildtool_dependency`.
