### ISSUE TITLE
broken rosdistro by manual addition of strands_morse@indigo

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/rosdistro#324]
This commit https://github.com/strands-project/rosdistro/commit/decdf632bea54c3181e95c6c36cb22e20af06f24 broke our rosdistro. Obviously this was added manually _without_ running bloom for it, Hence the tags don't exist in the release repo. Please remove and release "properly" again, i.e. using bloom!

See http://lcas.lincoln.ac.uk/jenkins/job/rosdistro-update/462/console:

```
Unable to fetch package.xml: Specified tag "release/indigo/strands_morse/0.0.8-0" is not a git tag of repository "https://github.com/strands-project-releases/strands_morse.git"
```

**Comment by marc-hanheide** [comment]
This has only been solved by taken strands_morse out of the indigo distribution. This is obviously not a proper fix, but at least the whole release process is not blocked any longer. @cburbridge should release this again via bloom.

**Comment by cburbridge** [comment]
Sorry, I started releasing strands_morse so added it to rosdistro, but then realised that it is held up by openni_wrapper so could not release it yet.  openni_wrapper os now indigo ready so after realeasing it strands_morse should be ok.

I always add manually to rosdistro when there is not yet an indigo release otherwise bloom complains it does not exist. Is it safe for me to next time allow bloom to add it?

**Comment by marc-hanheide** [comment]
It's correct that bloom complains, you'll need to add a new track with `-n`
flag and hen it will create it for you. Don't do it manually, it's
error-prone.

Marc

On 21 December 2014 at 19:51, Chris Burbridge notifications@github.com
wrote:

> Sorry, I started releasing strands_morse so added it to rosdistro, but
> then realised that it is held up by openni_wrapper so could not release it
> yet. openni_wrapper os now indigo ready so after realeasing it
> strands_morse should be ok.
> 
> I always add manually to rosdistro when there is not yet an indigo release
> otherwise bloom complains it does not exist. Is it safe for me to next time
> allow bloom to add it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/strands-project/rosdistro/issues/324#issuecomment-67782104
> .

## 

---

Dr. Marc Hanheide
Reader in Computer Science
Room MC3221B
University of Lincoln
Brayford Pool
Lincoln, LN6 7TS
Phone: +44 1522 88 6966
EMail: marc@hanheide.net
Web: http://www.hanheide.net
skype: mah99de
